<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\Orders\**" />
    <EmbeddedResource Remove="Views\Orders\**" />
    <None Remove="Views\Orders\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Views\Quotes\QuotesListPage.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Views\Quotes\QuotesListPage.xaml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="FodyWeavers.xml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="FodyWeavers.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AsyncAwaitBestPractices" Version="6.0.4" />
    <PackageReference Include="Com.Airbnb.Xamarin.Forms.Lottie" Version="4.0.11" />
    <PackageReference Include="Flurl" Version="3.0.2" />
    <PackageReference Include="Flurl.Http" Version="3.2.0" />
    <PackageReference Include="Forms.Controls.FlexButton" Version="0.14.1" />
    <PackageReference Include="Matcha.BackgroundService" Version="1.0.5478" />
    <PackageReference Include="Microsoft.AppCenter" Version="4.4.0" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="4.4.0" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="4.4.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
    <PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
    <PackageReference Include="SQLiteNetExtensions" Version="2.1.0" />
    <PackageReference Include="Xamarin.CommunityToolkit" Version="1.3.1" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2291" />
    <PackageReference Include="Xamarin.Essentials" Version="1.7.0" />
    <PackageReference Include="Xamarin.Forms.Visual.Material" Version="5.0.0.2291" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Interon.Roadlab.CMS\Interon.Roadlab.CMS.csproj" />
    <ProjectReference Include="..\..\Interon.Roadlab.Core\Interon.Roadlab.Core.csproj" />
    <ProjectReference Include="..\..\Interon.Roadlab.LIMS\Interon.Roadlab.LIMS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AppShell.xaml.cs">
      <DependentUpon>AppShell.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ClientRequests\ClientRequestComments.xaml.cs">
      <DependentUpon>ClientRequestComments.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ClientRequests\ClientRequestRequestLinePage.xaml.cs">
      <DependentUpon>ClientRequestRequestLinePage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ClientRequests\SiteListPage.xaml.cs">
      <DependentUpon>SiteListPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\HomePage.xaml.cs">
      <DependentUpon>HomePage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\HomePage2.xaml.cs">
      <DependentUpon>HomePage2.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\InfoPage.xaml.cs">
      <DependentUpon>InfoPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Registration\ResetPasswordPage.xaml.cs">
      <DependentUpon>ResetPasswordPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MessagePage.xaml.cs">
      <DependentUpon>MessagePage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ClientRequests\ClientRequestRequestPage.xaml.cs">
      <DependentUpon>ClientRequestRequestPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ClientRequests\ClientRequestSitePage.xaml.cs">
      <DependentUpon>ClientRequestSitePage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ClientRequests\ClientRequestPage.xaml.cs">
      <DependentUpon>ClientRequestPage.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\ClientRequests\ClientRequestListPage.xaml.cs">
      <DependentUpon>ClientRequestListPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\WarningPage.xaml.cs">
      <DependentUpon>WarningPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="AppShell.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Core\Controls\FlyoutHeader.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Core\Controls\Header.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Core\Controls\Rockface.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\AboutPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Branches\BranchListPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Developer\DeveloperPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ErrorPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Intro.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PlaceHolderPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Profile\ProfilePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Test.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ClientRequests\ClientRequestComments.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ClientRequests\ClientRequestPage.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ClientRequests\ClientRequestSitePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ClientRequestRequests\ClientRequestRequestPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Registration\LogOut.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Registration\NewRegisterPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\NoConnectivityPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Registration\RegisterPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Registration\ReRegisterPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Settings\SettingsPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\netstandard2.0\ref\" />
    <Folder Include="Core\NewFolder\" />
    <Folder Include="Views\QuoteRequests\" />
    <Folder Include="Views\Quotes\" />
  </ItemGroup>
</Project>