//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.4.1+ba29b91
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Interon.Roadlab.Web.Net.Core.Models.ContentModels
{
	// Mixin Content Type with alias "heroSection"
	/// <summary>_hero section</summary>
	public partial interface IHeroSection : IPublishedContent
	{
		/// <summary>Hero Content</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Strings.IHtmlEncodedString HeroContent { get; }

		/// <summary>Hero Large Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HeroLargeHeading { get; }

		/// <summary>Hero Right Image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.MediaWithCrops HeroRightImage { get; }

		/// <summary>Hero Short Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HeroShortDescription { get; }

		/// <summary>Hero Small Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HeroSmallHeading { get; }
	}

	/// <summary>_hero section</summary>
	[PublishedModel("heroSection")]
	public partial class HeroSection : PublishedContentModel, IHeroSection
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		public new const string ModelTypeAlias = "heroSection";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<HeroSection, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public HeroSection(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Hero Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroContent")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString HeroContent => GetHeroContent(this, _publishedValueFallback);

		/// <summary>Static getter for Hero Content</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Strings.IHtmlEncodedString GetHeroContent(IHeroSection that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(publishedValueFallback, "heroContent");

		///<summary>
		/// Hero Large Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroLargeHeading")]
		public virtual string HeroLargeHeading => GetHeroLargeHeading(this, _publishedValueFallback);

		/// <summary>Static getter for Hero Large Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHeroLargeHeading(IHeroSection that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "heroLargeHeading");

		///<summary>
		/// Hero Right Image: This image will automatically align to the centre. Must be 350px x 350px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroRightImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops HeroRightImage => GetHeroRightImage(this, _publishedValueFallback);

		/// <summary>Static getter for Hero Right Image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.MediaWithCrops GetHeroRightImage(IHeroSection that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(publishedValueFallback, "heroRightImage");

		///<summary>
		/// Hero Short Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroShortDescription")]
		public virtual string HeroShortDescription => GetHeroShortDescription(this, _publishedValueFallback);

		/// <summary>Static getter for Hero Short Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHeroShortDescription(IHeroSection that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "heroShortDescription");

		///<summary>
		/// Hero Small Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroSmallHeading")]
		public virtual string HeroSmallHeading => GetHeroSmallHeading(this, _publishedValueFallback);

		/// <summary>Static getter for Hero Small Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHeroSmallHeading(IHeroSection that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "heroSmallHeading");
	}
}
