//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.4.1+ba29b91
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Interon.Roadlab.Web.Net.Core.Models.ContentModels
{
	/// <summary>Home Page</summary>
	[PublishedModel("homePage")]
	public partial class HomePage : PublishedContentModel, IFooter, IRecentArticles, ISEO
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		public new const string ModelTypeAlias = "homePage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<HomePage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public HomePage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Desktop Image: Banner Image for desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("desktopImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops DesktopImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "desktopImage");

		///<summary>
		/// Mobile Image: Banner image for mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MobileImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "mobileImage");

		///<summary>
		/// Footer Accreditation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerAccreditation")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FooterAccreditation => global::Interon.Roadlab.Web.Net.Core.Models.ContentModels.Footer.GetFooterAccreditation(this, _publishedValueFallback);

		///<summary>
		/// FooterBee
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerBee")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FooterBee => global::Interon.Roadlab.Web.Net.Core.Models.ContentModels.Footer.GetFooterBee(this, _publishedValueFallback);

		///<summary>
		/// Method
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("method")]
		public virtual string Method => global::Interon.Roadlab.Web.Net.Core.Models.ContentModels.RecentArticles.GetMethod(this, _publishedValueFallback);

		///<summary>
		/// Related Articles Picker
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentArticlesPicker")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> RecentArticlesPicker => global::Interon.Roadlab.Web.Net.Core.Models.ContentModels.RecentArticles.GetRecentArticlesPicker(this, _publishedValueFallback);

		///<summary>
		/// OG Description: A one to two sentence description of your object.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("oGDescription")]
		public virtual string OGdescription => global::Interon.Roadlab.Web.Net.Core.Models.ContentModels.SEO.GetOGdescription(this, _publishedValueFallback);

		///<summary>
		/// OG Image: An image URL which should represent your object within the graph. And of size 1200x627
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("oGImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OGimage => global::Interon.Roadlab.Web.Net.Core.Models.ContentModels.SEO.GetOGimage(this, _publishedValueFallback);

		///<summary>
		/// OG Title: The title of your object as it should appear within the graph, e.g., "The Rock".
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("oGTitle")]
		public virtual string OGtitle => global::Interon.Roadlab.Web.Net.Core.Models.ContentModels.SEO.GetOGtitle(this, _publishedValueFallback);

		///<summary>
		/// OG Type: The type of your object, e.g., "article". Depending on the type you specify, other properties may also be required.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("oGType")]
		public virtual string OGtype => global::Interon.Roadlab.Web.Net.Core.Models.ContentModels.SEO.GetOGtype(this, _publishedValueFallback);

		///<summary>
		/// OG url: The canonical URL of your object that will be used as its permanent ID in the graph e.g. https://roadlab.co.za/services/geotechnical-road-investigations/geotechnical-road-investigations/#04
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("oGUrl")]
		public virtual string OGurl => global::Interon.Roadlab.Web.Net.Core.Models.ContentModels.SEO.GetOGurl(this, _publishedValueFallback);

		///<summary>
		/// Page Description: Enter a description for the page not Exceeding 160 characters.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageDescription")]
		public virtual string PageDescription => global::Interon.Roadlab.Web.Net.Core.Models.ContentModels.SEO.GetPageDescription(this, _publishedValueFallback);

		///<summary>
		/// Page Robots
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageRobots")]
		public virtual string PageRobots => global::Interon.Roadlab.Web.Net.Core.Models.ContentModels.SEO.GetPageRobots(this, _publishedValueFallback);

		///<summary>
		/// Page Title: Add the page title not exceeding 60 characters
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.1+ba29b91")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => global::Interon.Roadlab.Web.Net.Core.Models.ContentModels.SEO.GetPageTitle(this, _publishedValueFallback);
	}
}
