<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>8</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Flurl" Version="3.0.2" />
    <PackageReference Include="Flurl.Http" Version="3.2.0" />
    <PackageReference Include="fody" Version="6.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MethodTimer.Fody" Version="3.2.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SpatialFocus.MethodCache.Fody" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Interon.Roadlab.Core\Interon.Roadlab.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTO\ServiceRequests\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="FodyWeavers.xsd" />
  </ItemGroup>

</Project>
