<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Flurl.Http" Version="3.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Interon.Roadlab.Core\Interon.Roadlab.Core.csproj" />
    <ProjectReference Include="..\Interon.Roadlab.Lims\Interon.Roadlab.LIMS.csproj" />
  </ItemGroup>

</Project>
