// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Interon.Roadlab.LIMS.DTO.Quicktype;
//
//    var variants = Variants.FromJson(jsonString);

namespace Interon.Roadlab.LIMS.DTO.Quicktype
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Variants
    {
        [JsonProperty("serviceProvidersIDs")]
        public List<object> ServiceProvidersIDs { get; set; }

        [JsonProperty("id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Id { get; set; }

        [JsonProperty("product_id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ProductId { get; set; }

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("quantity")]
        public object Quantity { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("price")]
        public Price Price { get; set; }

        [JsonProperty("dateUpdated")]
        public DateTimeOffset DateUpdated { get; set; }

        [JsonProperty("active")]
        public bool Active { get; set; }

        [JsonProperty("sortingPriority")]
        public object SortingPriority { get; set; }

        [JsonProperty("propertyValues")]
        public List<object> PropertyValues { get; set; }

        [JsonProperty("location")]
        public object Location { get; set; }

        [JsonProperty("duration")]
        public long Duration { get; set; }

        [JsonProperty("supplierName")]
        public object SupplierName { get; set; }

        [JsonProperty("parent_id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ParentId { get; set; }

        [JsonProperty("category")]
        public List<Category> Category { get; set; }

        [JsonProperty("categoryBridges")]
        public List<object> CategoryBridges { get; set; }

        [JsonProperty("requiredAddon")]
        public List<object> RequiredAddon { get; set; }

        [JsonProperty("maxPrice")]
        public object MaxPrice { get; set; }

        [JsonProperty("minPrice")]
        public object MinPrice { get; set; }

        [JsonProperty("optionalAddOnIDs")]
        public List<object> OptionalAddOnIDs { get; set; }

        [JsonProperty("requiredAddOnIDs")]
        public List<object> RequiredAddOnIDs { get; set; }
    }

    public partial class Category
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial struct Price
    {
        public long? Integer;
        public string String;

        public static implicit operator Price(long Integer) => new Price { Integer = Integer };
        public static implicit operator Price(string String) => new Price { String = String };
    }

    public partial class Variants
    {
        public static Dictionary<string, Variants> FromJson(string json) => JsonConvert.DeserializeObject<Dictionary<string, Variants>>(json, Interon.Roadlab.LIMS.DTO.Quicktype.Converter.Settings);
    }

    

    internal class PriceConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Price) || t == typeof(Price?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.Integer:
                    var integerValue = serializer.Deserialize<long>(reader);
                    return new Price { Integer = integerValue };
                case JsonToken.String:
                case JsonToken.Date:
                    var stringValue = serializer.Deserialize<string>(reader);
                    return new Price { String = stringValue };
            }
            throw new Exception("Cannot unmarshal type Price");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (Price)untypedValue;
            if (value.Integer != null)
            {
                serializer.Serialize(writer, value.Integer.Value);
                return;
            }
            if (value.String != null)
            {
                serializer.Serialize(writer, value.String);
                return;
            }
            throw new Exception("Cannot marshal type Price");
        }

        public static readonly PriceConverter Singleton = new PriceConverter();
    }
}
