//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Interon.Roadlab.Web.Core.ContentModels
{
	/// <summary>Blog Article</summary>
	[PublishedModel("blogArticle")]
	public partial class BlogArticle : PublishedContentModel, IBannerImage, IBranchesIntersect, IHeroSection, IPageHeading, ISEO
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "blogArticle";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogArticle, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public BlogArticle(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Article Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("articleDate")]
		public DateTime ArticleDate => this.Value<DateTime>("articleDate");

		///<summary>
		/// Article Intersect Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("articleIntersectDescription")]
		public string ArticleIntersectDescription => this.Value<string>("articleIntersectDescription");

		///<summary>
		/// Article Intersect Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("articleIntersectImage")]
		public IPublishedContent ArticleIntersectImage => this.Value<IPublishedContent>("articleIntersectImage");

		///<summary>
		/// Blog Heading: Heading for blog article
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("blogHeading")]
		public string BlogHeading => this.Value<string>("blogHeading");

		///<summary>
		/// Category Page Toggle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("categoryPageToggle")]
		public bool CategoryPageToggle => this.Value<bool>("categoryPageToggle");

		///<summary>
		/// Expertise List
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("expertiseList")]
		public IEnumerable<StringItem> ExpertiseList => this.Value<IEnumerable<StringItem>>("expertiseList");

		///<summary>
		/// Grid
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("grid")]
		public Newtonsoft.Json.Linq.JToken Grid => this.Value<Newtonsoft.Json.Linq.JToken>("grid");

		///<summary>
		/// Home Page Toggle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("homePageToggle")]
		public bool HomePageToggle => this.Value<bool>("homePageToggle");

		///<summary>
		/// Industry List
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("industryList")]
		public IEnumerable<StringItem> IndustryList => this.Value<IEnumerable<StringItem>>("industryList");

		///<summary>
		/// Location List
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("locationList")]
		public IEnumerable<StringItem> LocationList => this.Value<IEnumerable<StringItem>>("locationList");

		///<summary>
		/// Banner Background Image: Image for heading background, image size 1920px X 1080px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("backImage")]
		public IPublishedContent BackImage => BannerImage.GetBackImage(this);

		///<summary>
		/// Branch Selector: The branch linked this content for email and contact purposes
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchSelector")]
		public IPublishedContent BranchSelector => BranchesIntersect.GetBranchSelector(this);

		///<summary>
		/// Hero Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("heroContent")]
		public IHtmlString HeroContent => HeroSection.GetHeroContent(this);

		///<summary>
		/// Hero Large Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("heroLargeHeading")]
		public string HeroLargeHeading => HeroSection.GetHeroLargeHeading(this);

		///<summary>
		/// Hero Right Image: This image will automatically align to the centre. Must be 350px x 350px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("heroRightImage")]
		public Umbraco.Core.Models.MediaWithCrops HeroRightImage => HeroSection.GetHeroRightImage(this);

		///<summary>
		/// Hero Short Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("heroShortDescription")]
		public string HeroShortDescription => HeroSection.GetHeroShortDescription(this);

		///<summary>
		/// Hero Small Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("heroSmallHeading")]
		public string HeroSmallHeading => HeroSection.GetHeroSmallHeading(this);

		///<summary>
		/// Page Heading Bottom: Bottom bold heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageHeadingBottom")]
		public string PageHeadingBottom => PageHeading.GetPageHeadingBottom(this);

		///<summary>
		/// Page Heading top: Top light heading add where applicable
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageHeadingTop")]
		public string PageHeadingTop => PageHeading.GetPageHeadingTop(this);

		///<summary>
		/// Page Icon: Add icon only if applicable
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageIcon")]
		public IPublishedContent PageIcon => PageHeading.GetPageIcon(this);

		///<summary>
		/// OG Description: A one to two sentence description of your object.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("oGDescription")]
		public string OGdescription => SEO.GetOGdescription(this);

		///<summary>
		/// OG Image: An image URL which should represent your object within the graph. And of size 1200x627
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("oGImage")]
		public IPublishedContent OGimage => SEO.GetOGimage(this);

		///<summary>
		/// OG Title: The title of your object as it should appear within the graph, e.g., "The Rock".
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("oGTitle")]
		public string OGtitle => SEO.GetOGtitle(this);

		///<summary>
		/// OG Type: The type of your object, e.g., "article". Depending on the type you specify, other properties may also be required.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("oGType")]
		public string OGtype => SEO.GetOGtype(this);

		///<summary>
		/// OG url: The canonical URL of your object that will be used as its permanent ID in the graph e.g. https://roadlab.co.za/services/geotechnical-road-investigations/geotechnical-road-investigations/#04
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("oGUrl")]
		public string OGurl => SEO.GetOGurl(this);

		///<summary>
		/// Page Description: Enter a description for the page not Exceeding 160 characters.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageDescription")]
		public string PageDescription => SEO.GetPageDescription(this);

		///<summary>
		/// Page Robots
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageRobots")]
		public string PageRobots => SEO.GetPageRobots(this);

		///<summary>
		/// Page Title: Add the page title not exceeding 60 characters
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageTitle")]
		public string PageTitle => SEO.GetPageTitle(this);
	}
}
