//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Interon.Roadlab.Web.Core.ContentModels
{
	/// <summary>Branch</summary>
	[PublishedModel("branch")]
	public partial class Branch : PublishedContentModel, IBlogSelector, IPageHeading, ISEO
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "branch";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Branch, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Branch(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Branch Accreditation link: Accreditation pdf
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchAccreditationLink")]
		public IPublishedContent BranchAccreditationLink => this.Value<IPublishedContent>("branchAccreditationLink");

		///<summary>
		/// Branch Address 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchAddress1")]
		public string BranchAddress1 => this.Value<string>("branchAddress1");

		///<summary>
		/// Branch Address 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchAddress2")]
		public string BranchAddress2 => this.Value<string>("branchAddress2");

		///<summary>
		/// Branch Address 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchAddress3")]
		public string BranchAddress3 => this.Value<string>("branchAddress3");

		///<summary>
		/// Branch Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchBackgroundImage")]
		public IPublishedContent BranchBackgroundImage => this.Value<IPublishedContent>("branchBackgroundImage");

		///<summary>
		/// Branch Cell Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchCellNumber")]
		public string BranchCellNumber => this.Value<string>("branchCellNumber");

		///<summary>
		/// Branch City
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchCity")]
		public string BranchCity => this.Value<string>("branchCity");

		///<summary>
		/// Branch Country
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchCountry")]
		public string BranchCountry => this.Value<string>("branchCountry");

		///<summary>
		/// Branch Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchEmail")]
		public string BranchEmail => this.Value<string>("branchEmail");

		///<summary>
		/// Branch Image: Branch manager image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchImage")]
		public IPublishedContent BranchImage => this.Value<IPublishedContent>("branchImage");

		///<summary>
		/// Branch Image Alt: Branch Image alt tag manager name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchImageAlt")]
		public string BranchImageAlt => this.Value<string>("branchImageAlt");

		///<summary>
		/// Branch Latitude
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchLatitude")]
		public string BranchLatitude => this.Value<string>("branchLatitude");

		///<summary>
		/// Branch Longitude
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchLongitude")]
		public string BranchLongitude => this.Value<string>("branchLongitude");

		///<summary>
		/// Branch Manager
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchManager")]
		public string BranchManager => this.Value<string>("branchManager");

		///<summary>
		/// Branch Map: Add google map iframe
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchMap")]
		public IHtmlString BranchMap => this.Value<IHtmlString>("branchMap");

		///<summary>
		/// Branch Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchName")]
		public string BranchName => this.Value<string>("branchName");

		///<summary>
		/// Branch Postal Code
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchPostalCode")]
		public string BranchPostalCode => this.Value<string>("branchPostalCode");

		///<summary>
		/// Branch Province
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchProvince")]
		public string BranchProvince => this.Value<string>("branchProvince");

		///<summary>
		/// Branch Telephone Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("branchTelephoneNumber")]
		public string BranchTelephoneNumber => this.Value<string>("branchTelephoneNumber");

		///<summary>
		/// Lims Branch Code
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("limsBranchCode")]
		public int LimsBranchCode => this.Value<int>("limsBranchCode");

		///<summary>
		/// Block Content Picker
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("blockContentPicker")]
		public IEnumerable<IPublishedContent> BlockContentPicker => BlogSelector.GetBlockContentPicker(this);

		///<summary>
		/// Page Heading Bottom: Bottom bold heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageHeadingBottom")]
		public string PageHeadingBottom => PageHeading.GetPageHeadingBottom(this);

		///<summary>
		/// Page Heading top: Top light heading add where applicable
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageHeadingTop")]
		public string PageHeadingTop => PageHeading.GetPageHeadingTop(this);

		///<summary>
		/// Page Icon: Add icon only if applicable
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageIcon")]
		public IPublishedContent PageIcon => PageHeading.GetPageIcon(this);

		///<summary>
		/// OG Description: A one to two sentence description of your object.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("oGDescription")]
		public string OGdescription => SEO.GetOGdescription(this);

		///<summary>
		/// OG Image: An image URL which should represent your object within the graph. And of size 1200x627
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("oGImage")]
		public IPublishedContent OGimage => SEO.GetOGimage(this);

		///<summary>
		/// OG Title: The title of your object as it should appear within the graph, e.g., "The Rock".
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("oGTitle")]
		public string OGtitle => SEO.GetOGtitle(this);

		///<summary>
		/// OG Type: The type of your object, e.g., "article". Depending on the type you specify, other properties may also be required.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("oGType")]
		public string OGtype => SEO.GetOGtype(this);

		///<summary>
		/// OG url: The canonical URL of your object that will be used as its permanent ID in the graph e.g. https://roadlab.co.za/services/geotechnical-road-investigations/geotechnical-road-investigations/#04
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("oGUrl")]
		public string OGurl => SEO.GetOGurl(this);

		///<summary>
		/// Page Description: Enter a description for the page not Exceeding 160 characters.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageDescription")]
		public string PageDescription => SEO.GetPageDescription(this);

		///<summary>
		/// Page Robots
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageRobots")]
		public string PageRobots => SEO.GetPageRobots(this);

		///<summary>
		/// Page Title: Add the page title not exceeding 60 characters
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageTitle")]
		public string PageTitle => SEO.GetPageTitle(this);
	}
}
