//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Interon.Roadlab.Web.Core.ContentModels
{
	// Mixin Content Type with alias "heroSection"
	/// <summary>_hero section</summary>
	public partial interface IHeroSection : IPublishedContent
	{
		/// <summary>Hero Content</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		IHtmlString HeroContent { get; }

		/// <summary>Hero Large Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		string HeroLargeHeading { get; }

		/// <summary>Hero Right Image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		Umbraco.Core.Models.MediaWithCrops HeroRightImage { get; }

		/// <summary>Hero Short Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		string HeroShortDescription { get; }

		/// <summary>Hero Small Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		string HeroSmallHeading { get; }
	}

	/// <summary>_hero section</summary>
	[PublishedModel("heroSection")]
	public partial class HeroSection : PublishedContentModel, IHeroSection
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "heroSection";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HeroSection, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public HeroSection(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Hero Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("heroContent")]
		public IHtmlString HeroContent => GetHeroContent(this);

		/// <summary>Static getter for Hero Content</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IHtmlString GetHeroContent(IHeroSection that) => that.Value<IHtmlString>("heroContent");

		///<summary>
		/// Hero Large Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("heroLargeHeading")]
		public string HeroLargeHeading => GetHeroLargeHeading(this);

		/// <summary>Static getter for Hero Large Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static string GetHeroLargeHeading(IHeroSection that) => that.Value<string>("heroLargeHeading");

		///<summary>
		/// Hero Right Image: This image will automatically align to the centre. Must be 350px x 350px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("heroRightImage")]
		public Umbraco.Core.Models.MediaWithCrops HeroRightImage => GetHeroRightImage(this);

		/// <summary>Static getter for Hero Right Image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static Umbraco.Core.Models.MediaWithCrops GetHeroRightImage(IHeroSection that) => that.Value<Umbraco.Core.Models.MediaWithCrops>("heroRightImage");

		///<summary>
		/// Hero Short Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("heroShortDescription")]
		public string HeroShortDescription => GetHeroShortDescription(this);

		/// <summary>Static getter for Hero Short Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static string GetHeroShortDescription(IHeroSection that) => that.Value<string>("heroShortDescription");

		///<summary>
		/// Hero Small Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("heroSmallHeading")]
		public string HeroSmallHeading => GetHeroSmallHeading(this);

		/// <summary>Static getter for Hero Small Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static string GetHeroSmallHeading(IHeroSection that) => that.Value<string>("heroSmallHeading");
	}
}
