//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Interon.Roadlab.Web.Core.ContentModels
{
	// Mixin Content Type with alias "pageHeading"
	/// <summary>_page heading</summary>
	public partial interface IPageHeading : IPublishedContent
	{
		/// <summary>Page Heading Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		string PageHeadingBottom { get; }

		/// <summary>Page Heading top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		string PageHeadingTop { get; }

		/// <summary>Page Icon</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		IPublishedContent PageIcon { get; }
	}

	/// <summary>_page heading</summary>
	[PublishedModel("pageHeading")]
	public partial class PageHeading : PublishedContentModel, IPageHeading
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "pageHeading";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PageHeading, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public PageHeading(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Page Heading Bottom: Bottom bold heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageHeadingBottom")]
		public string PageHeadingBottom => GetPageHeadingBottom(this);

		/// <summary>Static getter for Page Heading Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static string GetPageHeadingBottom(IPageHeading that) => that.Value<string>("pageHeadingBottom");

		///<summary>
		/// Page Heading top: Top light heading add where applicable
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageHeadingTop")]
		public string PageHeadingTop => GetPageHeadingTop(this);

		/// <summary>Static getter for Page Heading top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static string GetPageHeadingTop(IPageHeading that) => that.Value<string>("pageHeadingTop");

		///<summary>
		/// Page Icon: Add icon only if applicable
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageIcon")]
		public IPublishedContent PageIcon => GetPageIcon(this);

		/// <summary>Static getter for Page Icon</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedContent GetPageIcon(IPageHeading that) => that.Value<IPublishedContent>("pageIcon");
	}
}
