//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Interon.Roadlab.Web.Core.ContentModels
{
	/// <summary>Project</summary>
	[PublishedModel("project")]
	public partial class Project : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "project";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Project, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Project(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Project budget
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("projectBudget")]
		public string ProjectBudget => this.Value<string>("projectBudget");

		///<summary>
		/// Project client
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("projectClient")]
		public string ProjectClient => this.Value<string>("projectClient");

		///<summary>
		/// Project description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("projectDescription")]
		public string ProjectDescription => this.Value<string>("projectDescription");

		///<summary>
		/// Project Heading Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("projectHeadingBackgroundImage")]
		public IPublishedContent ProjectHeadingBackgroundImage => this.Value<IPublishedContent>("projectHeadingBackgroundImage");

		///<summary>
		/// Project Heading Bottom
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("projectHeadingBottom")]
		public string ProjectHeadingBottom => this.Value<string>("projectHeadingBottom");

		///<summary>
		/// Project Heading Top
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("projectHeadingTop")]
		public string ProjectHeadingTop => this.Value<string>("projectHeadingTop");

		///<summary>
		/// Project Image 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("projectImage1")]
		public IPublishedContent ProjectImage1 => this.Value<IPublishedContent>("projectImage1");

		///<summary>
		/// Project Image 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("projectImage2")]
		public IPublishedContent ProjectImage2 => this.Value<IPublishedContent>("projectImage2");

		///<summary>
		/// Project Image 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("projectImage3")]
		public IPublishedContent ProjectImage3 => this.Value<IPublishedContent>("projectImage3");

		///<summary>
		/// Project Links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("projectLinks")]
		public IHtmlString ProjectLinks => this.Value<IHtmlString>("projectLinks");

		///<summary>
		/// Project Location
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("projectLocation")]
		public string ProjectLocation => this.Value<string>("projectLocation");

		///<summary>
		/// Project Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("projectNumber")]
		public string ProjectNumber => this.Value<string>("projectNumber");

		///<summary>
		/// Project services
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("projectServices")]
		public string ProjectServices => this.Value<string>("projectServices");

		///<summary>
		/// Year of project
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("yearOfProject")]
		public string YearOfProject => this.Value<string>("yearOfProject");
	}
}
