<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
  <ItemGroup>
    <PackageReference Include="Our.Umbraco.FullTextSearch" Version="4.1.0" />
    <PackageReference Include="Umbraco.Cms.Core" Version="13.2.2" />
    <PackageReference Include="Umbraco.Cms.Infrastructure" Version="13.2.2" />
    <PackageReference Include="Umbraco.Cms.Web.Common" Version="13.2.2" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="13.2.2" />
  </ItemGroup>

</Project>
